# -*- coding: utf-8 -*-
"""Rock, Paper, Scissors.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mrzv6w1s3mEfbIcNgxP4AGdvj6YetrHV

# Bonnsy's Rock, Paper, and Scissors Game
"""

# Pics List & Imports
import os
import random
import time

pics ={"rock": """
    _______
---'   ____)
      (_____)
      (_____)
      (____)
---.__(___)
""",
"paper": """
     _______
---'    ____)____
           ______)
          _______)
         _______)
---.__________)
""",
"scissors": """
    _______
---'   ____)____
          ______)
       __________)
      (____)
---.__(___)
"""
}

# Ascii Art found here https://gist.github.com/wynand1004/b5c521ea8392e9c6bfe101b025c39abe

"""## Code and Logic

"""

# Clear the screen based on the operating system
def clear_screen():
    # For Windows
    if os.name == 'nt':
        os.system('cls')
    # For Mac and Linux
    else:
        os.system('clear')

# Function to ask if the player wants to play again
def ask_replay():
    replay = input("\nDo you want to play again? (y/n): ").lower()
    if replay == 'y' or replay == 'yes':
        play_game()  # Restart the game
    else:
        print("\nThanks for playing! Goodbye!")
        time.sleep(3)

# Def to play the game!
def play_game():
    # Prompt to start the game
    print('''
    ================================
          Welcome to Bonnsy's
    Rock, Paper, and Scissors game!
                ⋆★⋆
    Created by: Yangmee Vang, 2025
    ================================
            █▀█ █▀█ █▀▀ █▄▀
            █▀▄ █▄█ █▄▄ █░█

          █▀█ ▄▀█ █▀█ █▀▀ █▀█
          █▀▀ █▀█ █▀▀ ██▄ █▀▄

        █▀ █▀▀ █ █▀ █▀ █▀█ █▀█ █▀
        ▄█ █▄▄ █ ▄█ ▄█ █▄█ █▀▄ ▄█
    ================================
    Rules:
    - You will play against the computer.
    - Type R, P, or S to play against the computer when prompted.
    - Best out of 3 wins!
    ================================
    ''')

    input("To get started, please press enter.")

    # Variables
    computer_choice = ""
    computer_score = 0
    score = 0

    # Loop the play the game
    while score < 3:
      clear_screen()

      print(f"Player Score = {score} || Computer Score = {computer_score}")
      print("What do you play? Type R, P, or S.")
      player_choice = input().lower()

      if player_choice == "r":
        print("You chose: " + pics["rock"])
      elif player_choice == "p":
        print("You chose: " + pics["paper"])
      elif player_choice == "s":
        print("You chose: " + pics["scissors"])
      else:
        print("Invalid input. Please try again.")
        continue

      print("The computer plays:")
      # computer_choice = random.choice(list(pics.values()))
      computer_choice = pics["rock"]
      print(computer_choice)

      if player_choice == computer_choice:
        print("It's a tie!")
        time.sleep(3)
      elif(player_choice == "r") and computer_choice == pics["scissors"]:
        print("You win!")
        score += 1
        time.sleep(3)
      elif (player_choice == "p") and computer_choice == pics["rock"]:
        print("You win!")
        score += 1
        time.sleep(3)
      elif (player_choice == "s") and computer_choice == pics["paper"]:
        print("You win!")
        score += 1
        time.sleep(3)
      else:
        print("You lost against the computer!")
        computer_score += 1
        time.sleep(3)
        if computer_score == 3:
              print("💀 Game over! You lost " + str(computer_score) + " out of 3 rounds. 💀")
              ask_replay()
        continue

      # Win/Lose Condition
      if score == 3:
              print("\n🥇 Congrats! You won " + str(score) + " out of 3 rounds. 🥇")
              ask_replay()

"""# Play the Game"""

play_game()